### ISSUE TITLE
Problem Installing Hardhat

### ISSUE THREAD

**Issue by Anu27n** [deji-ice/MetaSecure-web3.0#2]
How to resolve this issue any idea?
<img width="735" alt="image" src="https://github.com/user-attachments/assets/f6bc6941-6d3d-4ef0-9c14-eea48f3732d8" />

**Comment by Anu27n** [comment]
@deji-ice bro can you help if u dont mind?

**Comment by deji-ice** [comment]
Hey! Sorry I didn't see this before, what's the command line you're using to setup? and can i see the full error please

**Comment by deji-ice** [comment]
@Anu27n i believe using this should set it up for you without issues
 `npx hardhat init`

**Comment by Anu27n** [comment]
@deji-ice i did this but script folder didnt come so i should create that manuallly.

**Comment by deji-ice** [comment]
@Anu27n  i created it manually yes

**Comment by Anu27n** [comment]
@deji-ice  rouston is deprecated which etherum u used?

**Comment by deji-ice** [comment]
> @deji-ice  rouston is deprecated which etherum u used?

I used sepolia testnet 

[sepolia](https://sepolia-faucet.pk910.de/)
